#!/usr/bin/env bash
#Execute the file 4, before task and this file execute stopped of the before file.
#Not used kill and killall
file_to_kill=$(pgrep ./4-to_infinity_and_beyond -f)
pkill -f "$file_to_kill"