#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.
#The signal SIGTERM
var=0
trap "echo 'I am invincible!!!'" SIGTERM
while [ $var ]
do
    echo "To infinity and beyond"
    sleep 2
done
