#!/usr/bin/env bash
#fizz buzz in bash

for i in {1..10}
do
    if  ! ((i % 3)) && ! ((i % 5))
    then
        echo 'FizzBuzz'
    elif ! ((i % 3))
    then
        echo 'Fizz'
    elif ! ((i % 5))
    then
        echo 'Buzz'
    else
        echo "$i"
    fi
done


