#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# and in the nine print 'Hi'
counter=0

while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo 'Hi'
  else
    echo 'Holberton School'
  fi
  ((counter++))
done
