#!/usr/bin/env bash
# print in 4 bad luck in 8 good look otherwise holberton school.

counter=0

while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo 'bad luck'
    elif [ $counter -eq 8 ]
    then
        echo 'good luck'
    else
        echo 'Holberton School'
    fi
    ((counter++))
done
