#!/usr/bin/env bash
# print in 4 bad luck in 8 good look otherwise holberton school.
counter=1

while [ $counter -le 20 ]
do
    case $counter in
    4*)
        echo $counter
        echo 'bad luck from China'
        ;;
    9*)
        echo $counter
        echo 'bad luck from Japan'
        ;;
    17*)
        echo $counter
        echo 'bad luck from Italy'
        ;;
    *)
        echo $counter
    esac
    ((counter++))
done

