#!/usr/bin/env bash
# print clock
hours=0

while [ $hours -le 12 ]
do
    echo 'Hour: ' $hours

    if [ $hours -eq 12 ]
    then
        break
    fi
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo $minutes
        ((minutes++))
    done
    ((hours++))
done
